version: '3.4'

services:
  f1driverback:
    image: ${DOCKER_REGISTRY-}f1driverback
    build:
        context: .
        dockerfile: F1DriverBack/Dockerfile
    ports:
        - "5000:80"
        
  bettingserviceback:
    image: ${DOCKER_REGISTRY-}bettingserviceback
    build:
      context: .
      dockerfile: BettingServiceBack/Dockerfile
    ports:
        - "5001:80"


  db:
    image: mysql:8.0
    container_name: db
    restart: always
    ports:
       - '3306:3306'
    environment:
        MYSQL_DATABASE: f1driver
        MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

  pma:
    depends_on:
     - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
     - '80:80'
    environment:
      PMA_HOST: db

volumes:
  dbdata:


