name: BettingServiceBack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore F1Driver/F1Driver.sln
    - name: Build
      run: dotnet build F1Driver/BettingServiceBack/BettingServiceBack.csproj --configuration Release
    - name: Test
      run: dotnet test F1Driver/F1Driver.sln --configuration Release
    - name: Docker Build & Push Action
      # You may pin to the exact commit or the version.
      # uses: mr-smithers-excellent/docker-build-push@a7fe6652db5c7274374844e81692992f5a2befb9
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        tags: v1, latest
        # Name of the Docker image
        image: sander1909/bettingserviceback
        # Target Docker registry
        registry: docker.io
        # Location of Dockerfile, if not Dockerfile in root directory
        dockerfile: F1Driver/BettingServiceBack/Dockerfile
        # Docker registry username
        username: ${{ secrets.DOCKER_USERNAME }}
        # Docker registry password
        password: ${{ secrets.DOCKER_PASSWORD }}
